apiVersion: mcpconnect.ansible.com/v1alpha1
kind: AnsibleMCPConnect
metadata:
  labels:
    app.kubernetes.io/name: ansiblemcpconnect
    app.kubernetes.io/instance: ansiblemcpconnect-sample
    app.kubernetes.io/part-of: ansible-ai-connect-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ansible-ai-connect-operator
  name: ansiblemcpconnect-sample
spec:
  no_log: false
  service_type: ClusterIP
  ingress_type: Route
  public_base_url: https://your_aap_public_base_url_here
